### PR TITLE
Updated - New Agents (Riptide)

### PR DESCRIPTION
**Pull request by TrueProfesional**

### CODE REVIEW

**Comment by Teamkiller324** [comment]
[csgo_agentschooser.zip](https://github.com/Franc1sco/Franug-AgentsChooser/files/7210084/csgo_agentschooser.zip)

This is a updated syntax format update of your fork :)

**Comment by Teamkiller324** [comment]
[csgo_agentschooser.zip](https://github.com/Franc1sco/Franug-AgentsChooser/files/7216624/csgo_agentschooser.zip)
Additional changes plus addition of sm_csgoagents_version and updated version from "1.2" to "1.2.0" and added some client validity checks to make sure the client is valid.

**Comment by crashzk** [comment]
Any chance to update to support agents patches?

I found an agents plugin that has, but it has some very annoying BUGS and no preview option.

[Agents.zip](https://github.com/Franc1sco/Franug-AgentsChooser/files/7219699/Agents.zip)

**Comment by crashzk** [comment]
@TrueProfesional I did a PR on my GitHub, just to send the compiled version with the new agents.

**Pull request merged**
